### ISSUE TITLE
change of license?

### ISSUE THREAD

**Issue by ks** [cosmos72/hyperluminal-mem#1]
Hi,
  any chance of using different license? Something non-infectious, which actually allows using the lib for projects?

Cheers,
  Karol

**Comment by cosmos72** [comment]
The serialization and deserialization part of this library, "hyperluminal-mem" is quite complete and I will soon release it under LLGPL license.
The object persistence "hyperluminal-db" is still in the design phase, and I will split it to a separate project - for the moment still under GPL.

**Comment by cosmos72** [comment]
Done. Hyperluminal-mem is now licensed under LLGPL.

**Comment by ks** [comment]
Thanks for this change!

Cheers
