### ISSUE TITLE
Make it possible to recover from "symbol not found" errors in mread-box/symbol

### ISSUE THREAD

**Issue by i-perminov** [cosmos72/hyperluminal-mem#11]
Would it be possible to signal a specific error (instead of a simple error with a string) in mread-box/symbol and to have the restart-case uncommented to let callers replace non-existent symbols? The error message should use sym-name instead of sym (because sym is always nil).
I can submit a pull request, but not sure if it is useful, because it is a trivial change.

Thanks,
Ilya

**Comment by cosmos72** [comment]
Hi, it's certainly possible.

If you look at the source code, there's already a commented-out fragment
 for doing exactly that (and it uses sym - which is always nil - instead of sym-name as you noted)
```Lisp
(defun mread-box/symbol (ptr index end-index)
   ;; ....
   (unless sym
      ;; ...
      #+(and)
      (error "Deserialization error: symbol ~A not found in package ~A" sym pkg-name)
      
      #-(and) ;; reading from *query-io* is always safe?
      (restart-case
            (error "Deserialization error: symbol ~A not found in package ~A" sym pkg-name)
         (store-symbol (new-sym)
            :report "Supply a new symbol."
            :interactive %read-interactive-symbol
            (setf sym new-sym)))))
```

I am thinking about the security implications of such a change:
I guess it means we start to unconditionally trust whoever controls the terminal where the Lisp process is running in.

**Comment by i-perminov** [comment]
It may be better and easier to just add a callback that's invoked on error. That would avoid any security and performance concerns. Something like:
`
(defvar *symbol-deserialization-error-handler*
  (lambda (sym-name pkg-name)
    (error "Deserialization error: symbol ~A not found in package ~A" sym-name pkg-name)))
`
and in the function
`           (let ((sym (find-symbol sym-name pkg)))
                (or sym (funcall *symbol-deserialization-error-handler* sym-name pkg-name)))
`

**Comment by cosmos72** [comment]
And leave security considerations (i.e. if someone - and who - can execute arbitrary code from the handler)
to the programmer that sets the handler?

That's definitely a minimalistic solution, I like it :)

**Comment by cosmos72** [comment]
Done, see commit f9d87004f653fd110b991ac4dfc932f0bbe4211d

**Comment by i-perminov** [comment]
Thanks!
