### ISSUE TITLE
Doesn't build - use of QL: in system file

### ISSUE THREAD

**Issue by quicklisp** [cosmos72/hyperluminal-mem#7]
When I prepare a quicklisp dist, all projects must build without Quicklisp present. The use of ql:quickload in the .asd file of this project prevents it from being built. Can you do it without QL:?

**Comment by cosmos72** [comment]
Thanks for the report.
Quicklisp was (ab)used to load hyperluminal-mem-test from (asdf:test-system :hyperluminal-mem).

Fixed in 0a4afcd - I replaced it with (asdf:load-system :hyperluminal-mem-test),
in any case it will be invoked only if somebody calls (asdf:test-system :hyperluminal-mem)
